version: '3.3'

networks: 
  mensageria:
  database:

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks: 
      - mensageria
 
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks: 
      - mensageria

  mongo:
    container_name: mongo
    image: mongo
    networks: 
      - database

  command-api:
    container_name: command-api
    build: ./command-api
    ports:
      - 8080:8080
    networks: 
      - mensageria
    environment: 
      KAFKA_TOPIC: todo-topic
      KAFKA_BROKER: kafka:9092
      