version: '3.3'

networks: 
  mensageria:
  database:

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks: 
      - mensageria
 
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks: 
      - mensageria

  mongo:
    container_name: mongo
    image: mongo
    networks: 
      - database

  command-api:
    container_name: producer
    build: ./command-api
    ports:
      - 8080:8080
    networks: 
      - mensageria
    environment: 
      KAFKA_TOPIC: todo-topic
      KAFKA_BROKER: kafka:9092
    
  command-processor:
    container_name: consumer
    build: ./command-processor
    networks: 
     - mensageria
    environment: 
      KAFKA_TOPIC: todo-topic
      KAFKA_BROKER: kafka:9092
      KAFKA_GROUPID: todo-group

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
      